# config.yaml

paths:
  # --- Input files ---
  netcdf_links_dir: 'data_raw/netcdf_links'
  locations_csv: 'data_raw/Cleaned_Location_Details.csv'
  raw_netcdf_dir: 'data_raw/netcdf'
  no2_csv: 'data_raw/Daily_NO2_Time_Series_Data.csv'  
  co_csv: 'data_raw/Daily_CO_Time_Series_Data.csv'   
  
  # --- Output files ---
  processed_pkl: 'data_processed/processed_data.pkl'
  scaler_pkl: 'data_processed/scaler.pkl'
  checkpoints_dir: 'results/checkpoints'
  plots_dir: 'results/plots'

data:
  # The size of the square patch to extract around each plant, in degrees.
  # 0.5 degrees is ~55km. You can adjust this.
  patch_size_deg: 0.5
  
model:
  image_size: 64 # The size we will resize our patches to for the ViT
  patch_size_vit: 8 # ViT patch size
  num_classes: 1 # For regression (predicting a single CO2 value)
  dim: 1024
  depth: 6
  heads: 16
  mlp_dim: 2048

training:
  epochs: 20
  batch_size: 32
  learning_rate: 0.001